# Generated by Django 5.1.7 on 2025-03-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_months', models.PositiveIntegerField(default=1)),
                ('limit_kwh', models.FloatField(help_text='Max energy allowed per month (kWh)')),
                ('overuse_charge_per_kwh', models.DecimalField(decimal_places=2, help_text='Charge per kWh over the limit', max_digits=6)),
                ('features', models.TextField(blank=True, help_text='Comma-separated features')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
